name: Duels
version: '${project.version}'
main: cz.helheim.duels.Duels
api-version: 1.18
authors: [ Maxbans9 ]
description: Duels plugin for Helheim network

commands:
  duel:
    description: "Duels a player"
  queue:
    aliases:
      - "q"
    description: "Usage: /queue <mode> <type> Example: /queue BuildUHC 1vs1"