name: Duels
version: '${project.version}'
main: cz.helheim.duels.Duels
api-version: 1.18
authors: [ Maxbans9 ]
description: Duels plugin for Helheim network

commands:
  autojoin:
    description: "This command automatically joins you to the game"
  duel:
    description: "Duels a player"